"""Boot context for the public guest booking portal's server-rendered shell
page.

`frontend-guest/vite.config.js`'s `frappeui({ frontendRoute: "/book", ... })`
builds the Vue app and copies its `index.html` to `www/book.html` (sibling of
this file, regenerated by every `yarn build` / `bench build --app hotel_erp`
-- never hand-edit it). Frappe serves that HTML, with the boot context this
module supplies, at the bare `/book` path and at every deep-linked sub-route
matched by the `website_route_rules` entry in `hooks.py`; Vue Router takes
over client-side navigation from there.

Unlike `www/pms.py` (the staff SPA, which redirects Guest to /login), this
page is deliberately open to Guest -- it's the public storefront. The only
gate is `Booking Portal Settings.enabled`: when off, this renders the closed
notice server-side (so a disabled portal doesn't even ship the SPA bundle to
a guest) and `hotel_erp.api.public_booking` independently refuses every
write/read call too, so the API can't be used to route around a page that
never mounted.
"""
from __future__ import annotations

import frappe

no_cache = 1


def get_context(context):
    settings = frappe.get_single("Booking Portal Settings")
    context.portal_enabled = bool(settings.enabled)
    context.closed_message = settings.closed_message

    context.boot = {
        "csrf_token": frappe.sessions.get_csrf_token(),
        "site_name": frappe.local.site,
        "portal_enabled": context.portal_enabled,
        "closed_message": context.closed_message,
    }
    return context
