"""Boot context for the Front Desk SPA's server-rendered shell page.

`frontend/vite.config.js`'s `frappeui({ frontendRoute: "/pms", ... })` builds
the Vue app and copies its `index.html` to `www/pms.html` (sibling of this
file, regenerated by every `yarn build` / `bench build --app hotel_erp` --
never hand-edit it). Frappe serves that HTML, with the boot context this
module supplies, at the bare `/pms` path and at every deep-linked sub-route
matched by the `website_route_rules` entry in `hooks.py`; Vue Router takes
over client-side navigation from there.
"""
from __future__ import annotations
from urllib.parse import urlencode

import frappe

no_cache = 1


def get_context(context):
    if frappe.session.user == "Guest":
        # frappe.throw(..., frappe.PermissionError) does NOT redirect here --
        # confirmed live against a running site while building this, it
        # renders a 403 "Not Permitted" page with a Login button instead (see
        # frappe.website.page_renderers.not_permitted_page). frappe.redirect
        # (raises frappe.exceptions.Redirect, caught by the renderer) is the
        # real mechanism -- exactly what core's own www/desk.py (the /desk
        # route) uses for this same "Guest hit a login-required page" case.
        frappe.redirect(f"/login?{urlencode({'redirect-to': frappe.request.path})}")

    context.boot = {
        "csrf_token": frappe.sessions.get_csrf_token(),
        "site_name": frappe.local.site,
        "user": frappe.session.user,
        "user_info": {
            "full_name": frappe.utils.get_fullname(frappe.session.user),
            "roles": frappe.get_roles(frappe.session.user),
        },
    }
    return context
